
last_names = {


    'O\'brien': 'O’brien',
    'Peirò': 'Peiro',
    'W.  Brown': 'W. Brown',
    'Harris?': 'Harris',
    'Nurse?': 'Nurse',
    'O\'donnell': 'O\'Donnell',
    'N\'Diaye': 'N\'diaye',
    'M Rodriguez': 'M. Rodriguez',
    'Godin': 'Godín',
    'O\'Reilly': 'O’Reilly',
    'Gudiño': 'Gudino',
    'M. Kelly': 'M Kelly',
    'van der Haar': 'Van der Haar',
    'NIxon': 'Nixon',
    'T?': 'T',

    'Meiner': 'Meißner',
    'Zuazu': 'Zuazú',
    'Debrito': 'DeBrito',
    'Popo': 'Popó',
    'J Sa': 'J. Sa',
    'Estácio': 'Estacio',
    'De los Rios': 'de los Rios',
    'perry': 'Perry',
    'FLorie': 'Florie',
    'Mathéus': 'Matheus',
    'OConnor': 'O\'Connor',
    'Tehel': 'tehel',
    'O’Neill': 'O\'Neill',
    'hosie': 'Hosie',
    'Higuain': 'Higuaín',
    'De la Peña': 'De La Pena',
    'W. Pérez': 'W. Perez',
    'J. Macauley': 'J. MacAuley',
    'GLover': 'Glover',
    '2-2': '2-2.',
    'J. Guzman': 'J. Guzmán',
    'T. cunningham': 'T. Cunningham',
    'den Ouden': 'Den Ouden',
    'Ohara': 'O\'Hara',


    'A Korbiel': 'A. Korbiel',
    'pen': 'PEN',
    'Chatton?': 'Chatton',
    'COker': 'Coker',
    'P .Wilson': 'P. Wilson',
    'MacAulay': 'Macaulay',
    'J.Martinez': 'J.Martínez',
    'Da?us': 'Daus',
    'MCAuley': 'McAuley',
    'M Blanco': 'M. Blanco',

    'O\'hare': 'O\'Hare',
    'H?': 'H?????',
    'LaVrinenko': 'Lavrinenko',
    'Mckillop': 'McKillop',
    'A???': 'A',
    'Dasilva': 'DaSilva',
    'Senkler.': 'Senkler',


    'Baré': 'Bare',
    'C Miranda': 'C. Miranda',
    'Malbrán': 'Malbran',
    'penalty kick​': 'penalty kick',
    'B Butler': 'B. Butler',
    'Japones': 'Japonês',
    'Förster': 'Forster',
    'A jackson': 'A. Jackson',
    'MacIntosh': 'Macintosh',
    'Round': 'Round:',

    'C. Ramírez': 'C. Ramirez',
    'HighField': 'Highfield',
    'Feijão': 'Feijao',
    'S Decker': 'S. Decker',
    'Roman': 'Román',
    '? Sasso': 'Sasso',
    'D\'Agostino': 'D’Agostino',
    'Beland Goyette': 'Beland-Goyette',
    'L. Rodriguez': 'L. Rodríguez',
    'E.Rodríguez': 'E. Rodriguez',
    'E.Rodriguez': 'E. Rodriguez',

    'Agüero': 'Aguero',
    'Gracián': 'Gracian',
    'Cámpora': 'Campora',
    
    '?.Luna': 'Luna',
    'Winter?': 'Winter',
    'Baéz': 'Baez',
    '?.Herrera': 'Herrera',
    '?.Soto': 'Soto',
    'Thomson.': 'Thomson',
    '?.Vera': 'Vera',
    '? Dixon': 'Dixon',
    '?.Jiménez': 'Jimenez',
    'Jiménez': 'Jimenez',
    'Brennan?': 'Brennan',
    
    'nelson': 'Nelson',
    '. Brown': 'Brown',
    '?.Cornejo': 'Cornejo',
    'martin': 'Martin',
    '?. Solomon': 'Solomon',
    'Muñoz': 'Munoz',
    'Jones?': 'Jones',
    'Lauder?': 'Lauder',
    '?.Solorzano': 'Solorzano',
    'GERMANY': 'Germany', # huh?
    'Forrester.': 'Forrester',
    '?. Howell': 'Howell',
    '?. Estrada': 'Estrada',
    '?.Pérez': 'Perez',
    'Pérez': 'Perez',
    
    'Mcnamara': 'McNamara',
    'Mckee': 'McKee',
    
    
    'Avilés': 'Aviles',
    'Álvarez': 'Alvarez',
    'Aguilá': 'Aguila',
    'Águila': 'Aguila',
    'Arrúa': 'Arrua',
    'Alcázar': 'Alcazar',
    'Alcántara': 'Alcantara',
    'Arévalo': 'Arevalo',
    'Aírton': 'Airton',
    'Antón': 'Anton',
    'Arzúaga': 'Arzuaga',
    'Aléncar': 'Alencar',
    'Araújo': 'Araujo',
    'Adaílton': 'Adailton',
    'Ângelo': 'Angelo',
    'Ademílson': 'Ademilson',
    'Acuña': 'Acuna',
    'Acourt': 'A\'Court',
    
    'Benítez': 'Benitez',
    'Bergará': 'Bergara',
    'Bermúdez': 'Bermudez',
    'Bordón': 'Bordon',
    'Brandão': 'Brandao',
    'Bareño': 'Bareno',
    'Belén': 'Belen',
    'Bruñel': 'Brunel',
    'Bobó': 'Bobo',
    'Bobô': 'Bobo',
    'Bené': 'Bene',
    'Bilú': 'Bilu',
    'Bergström': 'Bergstrom',
    'Barberón': 'Barberon',
    'Braithwaite.': 'Braithwaite',
    'Bartô': 'Barto',
    'Boyé': 'Boye',
    'Báez': 'Baez',
    'Bolívar': 'Bolivar',

    'Cabañas': 'Cabanas',
    'Calderón': 'Calderon',
    'Cañon': 'Canon',
    'Cañón': 'Canon',
    'Castañon': 'Castañón',
    'Cesar': 'César',
    'Chacón': 'Chacon', 
    'Cícero': 'Cicero',
    'Cláudio': 'Claudio',
    'Caté': 'Cate',
    'Cabillón': 'Cabillon',
    'Corrêa': 'Correa',
    'Cáceres': 'Caceres',
    'Chacón': 'Chacon',
    'Carlés': 'Carles',
    'Córdoba': 'Cordoba',
    'Clariá': 'Claria',
    'Canário': 'Canario',
    'Chalá': 'Chala',
    'Chávez': 'Chavez',
    'Caíco': 'Caico',
    'Carreño': 'Carreno',
    'Cléo': 'Cleo',
    'Cortéz': 'Cortez',
    'Cristián': 'Cristian',
    'Cazaubón': 'Cazaubon',
    'Canón': 'Canon',
    'Ceará': 'Ceara',

    'Daguia': 'DaGuia',
    'Derobertis': 'DeRobertis',
    'Da Cruz': 'da Cruz',
    'del Campo': 'Del Campo',
    'De La Cruz': 'de la Cruz',
    'De la Cruz': 'de la Cruz',
    'Da Silva': 'da Silva',
    'Durán': 'Duran',
    'Dirçeu': 'Dirceu',
    'De León': 'de Leon',
    'De Robertis': 'de Robertis',
    'De Ciancio': 'de Ciancio',
    'Díez': 'Diez',
    'Da Cunha': 'da Cunha',
    'Del Campo.': 'Del Campo',
    'Di Stéfano': 'Di Stefano',
    'Dênis': 'Denis',
    'Deoliveira': 'DeOliveira',
    'De La Peña': 'De la Peña',
    'Dinélson': 'Dinelson',
    'Dodó': 'Dodô',
    'Darío': 'Dario',
    'de Souza': 'De Souza',
    'Doménech': 'Domenech',
    'DeMarchi': 'Demarchi',
    'Devivo': 'DeVivo',
    'De Los Santos': 'De los Santos',
    'Dely Valdéz': 'Dely Valdez',
    'DAlessandro': 'D\'Alessandro',
    'Digao': 'Digão',
    'Demenezes': 'DeMenezes',
    'De Koven': 'de Koven',

    'Espíndola': 'Espindola',
    'Espíndola': 'Espindola',
    'Echevarría': 'Echevarria',
    'Éwerthon': 'Ewerthon',
    'Everton': 'Éverton',
    'Egídio': 'Egidio',
    'Espínola': 'Espinola',
    'Enría': 'Enria',
    'Éderson': 'Ederson',
    'Élton': 'Elton',
    'Éder': 'Eder',
    'Élkeson': 'Elkeson',
    'Émerson': 'Emerson',
    'Ediglê': 'Edigle',
    'Enílton': 'Enilton',
    'Enríquez': 'Enriquez',

    'Farfán': 'Farfan',
    'Forlán': 'Forlan',
    'Félix': 'Felix',
    'Farías': 'Farias',
    'Fágner': 'Fagner',
    'Fábio': 'Fabio',

    'Gámez': 'Gamez',
    'Gonçalves': 'Goncalves',
    'Galván': 'Galvan',
    'Gélson': 'Gelson',
    'Girón': 'Giron',
    'Gílson': 'Gilson',
    'Geílson': 'Geilson',
    'Giménez': 'Gimenez',
    'Gláuber': 'Glauber',
    'González': 'Gonzalez',
    'Gonzàlez': 'Gonzalez',
    'Gómez': 'Gomez',
    'Gonçálvez': 'Goncalvez',

    'Héctor': 'Hector',
    'Hormazábal': 'Hormazabal',
    'Héber': 'Heber',
    'Husaín': 'Husain',    
    'Hélder': 'Helder',
    'Hélton': 'Helton',
    'Héverton': 'Heverton',

    'Iguarán': 'Iguaran',
    'Íbson': 'Ibson',
    'Iván': 'Ivan',
    'Ibáñez': 'Ibanez',
    'Ibañez': 'Ibanez',
    'Izaías': 'Izaias',
    'Idário': 'Idario',
    'Ilan': 'Ilán',
    'Indio': 'Índio',
    'Itaqui': 'Itaquí',

    'Josué': 'Josue',
    'Jóbson': 'Jobson',
    'Joílson': 'Joilson',
    'Jaílton': 'Jailton',
    'Jó': 'Jo',    
    'Jô': 'Jo',
    'João': 'Joao',
    'Jéci': 'Jeci',
    'Jonílson': 'Jonilson',
    'Jáuregui': 'Jauregui',
    'Jadílson': 'Jadilson',
    'Juárez': 'Juarez',

    'Kahe': 'Kahê',

    'LeFevre': 'Lefevre',
    'Luís': 'Luis',
    'Landáburu': 'Landaburu',
    'lawrence': 'Lawrence',

    'Muñiz': 'Muniz',
    'Morón': 'Moron',
    'Mazarópi': 'Mazaropi',
    'Mcateer': 'McAteer',
    'MacAuley': 'Macauley',
    'Marín': 'Marin',
    'Mendonça': 'Mendonca',
    'Marroquín': 'Marroquin',
    'Maldonado.': 'Maldonado',
    'Macfarlane': 'MacFarlane',
    'Macgregor': 'MacGregor',
    'Mimí': 'Mimi',
    'Messías': 'Messias',
    'Macpherson': 'MacPherson',
    'Míguez': 'Miguez',
    'Mesías': 'Mesias',
    'Maurício': 'Mauricio',
    'Maranhao': 'Maranhão',
    'mcPherson': 'McPherson',
    'Möller': 'Moller',
    'Márquez': 'Marquez',
    'Médici': 'Medici',
    'MacKay': 'Mackay',
    'Montaño': 'Montano',
    'Maurílio': 'Maurilio',
    'Macbay': 'MacBay',
    'Meléndez': 'Melendez',
    'Mádson': 'Madson',
    'Martín': 'Martin',
    'Morán': 'Moran',
    'Mourino': 'Mouriño',
    'Múñoz': 'Munoz',
    'Mourín': 'Mourin',
    'Magalhaes': 'Magalhães',

    'Núñez': 'Nunez',
    'Núñez': 'Nunez',
    'Noriega]': 'Noriega',
    'Noé': 'Noe',
    'Nené': 'Nenê',
    'Nélson': 'Nelson',
    'Néstor': 'Nestor',
    'Nílton': 'Nilton',


    'Ortuño': 'Ortuno',
    'Ortíz': 'Ortiz',
    'O\'neill': 'O\'Neill',
    'Orsi.': 'Orsi',
    'Obregón': 'Obregon',
    'Odell': 'O\'Dell',
    'Oliván': 'Olivan',
    'Ordóñez': 'Ordonez',
    'Ortegón': 'Ortegon',

    'Padín': 'Padin',
    'Peláez': 'Pelaez',
    'Pachín': 'Pachin',
    'Patricio': 'Patrício',
    'Palácios': 'Palacios',
    'Paulao': 'Paulão',
    'Padrón': 'Padron',
    'Piñeiro': 'Pineiro',
    'Patiño': 'Patino',
    'Perdigao': 'Perdigão',
    'pearce': 'Pearce',

    'Quirós': 'Quiros',
    'Quiñones': 'Quinones',

    'Ruíz': 'Ruiz',
    'Rendon': 'Rendón',
    'Ramón': 'Rámon',
    'Rômulo': 'Romulo',
    'Rogéiro': 'Rogeiro',
    'Róbston': 'Robston',
    'Revélez': 'Revelez',
    'Rincón': 'Rincon',
    'Réver': 'Rever',


    'Solís': 'Solis',
    'Somália': 'Somalia',
    'Soría': 'Soria',
    'Suárez': 'Suarez',
    'Sabará': 'Sabara',
    'Sanchís': 'Sanchis',
    'Sjöberg': 'Sjoberg',
    'Sesúmaga': 'Sesumaga',
    'Susán': 'Susan',
    'Seguí': 'Segui',
    'Solá': 'Sola',
    'Sérgio': 'Sergio',
    'Santín': 'Santin',
    'Sá': 'Sa',
    'Simões': 'Simoes',
    'Sorín': 'Sorin',
    'Seré': 'Sere',
    'Santamaria': 'Santamaría',
    'Sílvio': 'Silvio',
    'Schäfer': 'Schafer',

    'Toró': 'Toro',
    'Téllez': 'Tellez',
    'Telê': 'Tele',
    'Tomás': 'Tomas',
    'Treviño': 'Trevino',
    'Törnqvist': 'Tornqvist',
    'Totó': 'Toto',
    'Tartá': 'Tarta',

    'Urzáiz': 'Urzaiz',
    'Umaña': 'Umana',
    'Urdinarán': 'Urdinaran',
    'Úeslei': 'Ueslei',

    'Valdés': 'Valdes',
    'Valdéz': 'Valdez',
    'Vásquez': 'Vasquez',
    'Vázquez': 'Vazquez',
    'Verón': 'Veron',
    'Vílchez': 'Vilchez',
    'Velázquez': 'Velazquez',
    'Vinícius': 'Vinicius',
    'Velásquez': 'Velasquez',
    'Vantolrá': 'Vantolra',
    'Vítor': 'Vitor',
    'Vágner': 'Vagner',
    'Viafara': 'Viáfara',
    'Válber': 'Valber',
    'Van Der Beck': 'Van der Beck',
    'Vevé': 'Veve',
    'Valdívia': 'Valdivia',
    'Vélber': 'Velber',

    'Wágner': 'Wagner',

    'Yánez': 'Yanez',
    'Yañez': 'Yanez',

    'Zúñiga': 'Zuniga',
    'Zúñiga': 'Zuniga',
    'Zé Elias': 'Ze Elias',
    'Zé Luis': 'Zé Luís',
    'Zandoná': 'Zandona',
    'Zárraga': 'Zarraga',
    }
