partial = {
#'S????': 'S',
#'M?????': 'M?',
#'Pol?': 'Pol',
#'K?ist': 'Kist',

'A Lopez': 'A. Lopez',
'A. López': 'A. Lopez',
'C Rodriguez': 'C. Rodriguez',
'c. Rodriguez': 'C. Rodriguez',
'C. Rodríguez': 'C. Rodriguez',
'R. Martínez': 'R. Martinez',
'A.González': 'A. Gonzalez',
'A.Gonzalez': 'A. Gonzalez',
'F. Fernández': 'F. Fernandez',
'A. Martínez': 'A. Martinez',
'W. Martínez': 'W. Martinez',
'R. Rodríguez': 'R. Rodriguez',
'A. Martín': 'A. Martin',
'R. Gómez': 'R. Gomez',
'J. García': 'J. Garcia',
'H. González': 'H. Gonzalez',
'C. Husaín': 'C. Husain',
'R.García': 'R. Garcia',
'R.Garcia': 'R. Garcia',
'A. Fernández': 'A. Fernandez',
'R. Macmahon': 'R. MacMahon',
'J. Pérez': 'J. Perez',
'W. Dos Santos': 'W. dos Santos',
'R.Martínez': 'R. Martinez',
'R.Martinez': 'R. Martinez',
'J. Dos Santos': 'J. dos Santos',
'J Phillips': 'J. Phillips',
'F. De Groof': 'F. de Groof',
'D Stewart': 'D. Stewart',
'J. Vázquez': 'J. Vazquez',
'C. Martín': 'C. Martin',
'M.Rodriguez': 'M. Rodriguez',
'M.Rodríguez': 'M. Rodriguez',
'De La Torre': 'de la Torre',
'W. Dasilva': 'W. DaSilva',
'A Gonzalez': 'A. Gonzalez',
'A. González': 'A. Gonzalez',
'R. Pérez': 'R. Perez',
'J. Fernández': 'J Fernandez',
'F. Pérez': 'F. Perez',
'D. Johnson': 'D Johnson',
'J. Rodríguez': 'J. Rodriguez',
'J. Hugo?': 'J. Hugo',
'O.Ramirez': 'O. Ramirez',
'O.Ramírez': 'O. Ramirez',
'V. Juárez': 'V. Juarez',
'V. Júarez': 'V. Juarez',
'R. Ramírez': 'R. Ramirez',
'R. Fernández': 'R. Fernandez',
}
