
international = {

    'Trinidad & Tobago Olympic Team': 'Trinidad and Tobago Olympic',

    'Trinidad and Tobago U23': 'Trinidad and Tobago U-23',

    'Canada U23': 'Canada U-23',

    'Benín': 'Benin',
    'Libano': 'Lebanon',
    'Tahití': 'Tahiti',
    'Guinea Bissau': 'Guinea-Bissau',
    'Etiopia': 'Ethiopia',
    'Botsuana': 'Botswana',

    'Libia': 'Libya',
    'Comoras': 'Comoros',

    'Serbia Y Montenegro': 'Serbia and Montenegro',

    'Nueva Caledonia': 'New Caledonia',
    'Islas Salomón': 'Solomon Islands',
    'Zimbabue': 'Zimbabwe',

    'Arabia Saudita': 'Saudi Arabia',
    'Congo Rd': 'DR Congo',

    'Uzbekistán': 'Uzbekistan',
    'Omán': 'Oman',
    'Túnez': 'Tunisia',
    'Cabo Verde': 'Cape Verde',
    'Martinica': 'Martinique',

    'Países Bajos': 'Netherlands',
    'Irán': 'Iran',
    'Emiratos Árabes Unidos': 'United Arab Emirates',
    'Malaui': 'Malawi',
    'Eslovenia': 'Slovenia',
    'Camerún': 'Cameroon',
    'Costa De Marfil': 'Ivory Coast',
    'Eslovaquia': 'Slovakia',
    'Irlanda': 'Ireland',
    'Islas Feroe': 'Faeroe Islands',

    'Kazajistán': 'Kazakhstan',
    'Luxemburgo': 'Luxembourg',
    
    'Islandia': 'Iceland',

    'Moldavia': 'Moldova',

    'Lituania': 'Lithuania',
    'Bielorrusia': 'Belarus',
    #'Letonia': 
    'Azerbaiyán': 'Azerbaijan',

    'Eduador': 'Ecuador',

    'Sudáfrica': 'South Africa',
    'Egipto': 'Egypt',

    'Italia': 'Italy',

    'Checoslovaquia': 'Czechoslovakia',
    'Bélgica': 'Belgium',
    'Hungría': 'Hungary',
    'Noruega': 'Norway',
    'Antillas Holandesas': 'Dutch Antilles',
    'Inglaterra': 'England',
    'República Federal De Alemania': 'Germany',
    'Gales': 'Wales',
    'Marruecos': 'Morocco',
    'Dinamarca': 'Denmark',
    'Ucrania': 'Ukraine',


    'Bosnia-Herzegovina': 'Bosnia and Herzegovina',
    'Bosnia-Hercegov.': 'Bosnia and Herzegovina',
    'St Croix': 'St. Croix',
    'United States Maccabiah': 'United States Maccabi',
    'USSR Olympic Team': 'USSR Olympic',
    'U.S.S.R Olympic': 'USSR Olympic',
    'U.S.S.R. Olympic': 'USSR Olympic',
    'U.S.S.R U-20': 'U.S.S.R. U-20',

    'USSR U-20': 'U.S.S.R. U-20',
    'USSR U-17': 'U.S.S.R. U-17',
    'U.S.S.R U-17': 'U.S.S.R. U-17',

    'Checoslovaquia Sub-17': 'Czechoslovakia U-17',

    'US Maccabi': 'United States Maccabi',
    'US Olympic': 'United States Olympic',

    'Canada College': 'Cañada College',

    'United States Military Academy': 'West Point',


    # By confederation.


    # CONCACAF

    'British Honduras': 'Belize',

    'Canadá': 'Canada',

    'Guadalupe': 'Guadaloupe',
    'Panamá': 'Panama',
    'Suiza': 'Switzerland',
    'Turquía': 'Turkey',
    'Alemania': 'Germany',
    'Croacia': 'Croatia',
    'Francia': 'France',
    'Holanda': 'Netherlands',
    'Grecia': 'Greece',
    'Suecia': 'Sweden',
    'Finlandia': 'Finland',
    'Rusia': 'Russia',
    'Belice': 'Belize',

    'Rp China': 'China',
    'Rep. Checa': 'Czech Republic',
    'Corea Del Norte': 'North Korea',
    'Corea Del Sur': 'South Korea',

    'Polonia': 'Poland',
    'Brasil': 'Brazil',
    
    'Jordania': 'Jordan',

    'España': 'Spain',

    'Japón': 'Japan',

    'Escocia': 'Scotland',

    'Nueva Zelanda': 'New Zealand',

    'Haití': 'Haiti',
    'US Virgin Islands': 'U.S. Virgin Islands',
    #Dominican Rep>, <Team: Dominican Rep.>]
    'San Vicente & Granadinas': 'Saint Vincent and the Grenadines',
    'Saint Vincent and The Grenadines': 'Saint Vincent and the Grenadines',
    'St Vincent': 'Saint Vincent and the Grenadines',
    'Cote d\'Ivoire': 'Côte d\'Ivoire',
    'Rumania': 'Romania',
    'Dominican Rep': 'Dominican Republic',
    'British Virgin Isl': 'British Virgin Islands',
    'St. Thomas': 'Saint Thomas',
    'French St Martin': 'French Saint Martin',
    'St. Croix': 'Saint Croix',

    'Saint Vincent and Grenadines': 'Saint Vincent and the Grenadines',
    'St. Vincent and Grenadines': 'Saint Vincent and the Grenadines',
    'Netherlands Antilles': 'Curacao',

    'Demerara': 'Guyana',
    'British Guyana': 'Guyana',
    'French Guyana': 'French Guiana',
    'Dutch Guiana': 'Suriname',

    'St. Kitts & Nevis': 'Saint Kitts and Nevis',
    'St Kitts': 'Saint Kitts and Nevis',
    'St.Kitts & Nevis': 'Saint Kitts and Nevis',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',



    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',

    'Surinam': 'Suriname',

    'St. Lucia': 'Saint Lucia',
    'St Lucia': 'Saint Lucia',

    'Turks and Caicos': 'Turks and Caicos Islands',

    'Faeroe Islands': 'Faroe Islands',
    'Fr. Saint Martin': 'Saint Martin',

    'Haití': 'Haiti',
    'Bermuda Under-23': 'Bermuda U-23',

    'Trinidad Y Tobago': 'Trinidad and Tobago',
    'Trinidad & Tobago': 'Trinidad and Tobago',
    'Trinidad/Tobago': 'Trinidad and Tobago',

    #'España': 'Spain',

    'Irak': 'Iraq',
    'Southafrica': 'South Africa',
    'Nueva Zealandia': 'New Zealand',

    
    'México': 'Mexico', 
    'Perú': 'Peru', 


    'Côte d\'Ivoire (Ivory Coast)': 'Côte d\'Ivoire',
    'Ivory Coast': 'Côte d\'Ivoire',
    'German Democratic Republic': 'East Germany',
    'German DR': 'East Germany',
    'Germany FR': 'West Germany',
    'FR Germany': 'West Germany',
    'Korea DPR': 'North Korea',
    'Korea Republic': 'South Korea',

    'Estados Unidos': 'United States',
    'USNT': 'United States',
    'USA': 'United States',
    'U.S. USNT': 'United States',

    'U.S. U-15 BNT': 'United States U-15',

    'U.S. U-17': 'United States U-17',
    'U.S. U-17 MNT': 'United States U-17',
    'U.S. U-17 MNT 95': 'United States U-17',

    'U.S. U-18': 'United States U-18',
    'U.S. U-18 MNT': 'United States U-18',

    'U.S. U-20': 'United States U-20',
    'U.S. U-20 MNT': 'United States U-20',

    'U.S. U-23 MNT': 'United States U-23',
    'U.S. U-23': 'United States U-23',

    'Indonesia Selection': 'Indonesia XI',


    'Dutch Antilles': 'Netherlands Antilles',
    'South Korea National Team': 'South Korea',
    'Australian National Team': 'Australia',
    'Chinese National Team': 'China',
    'Haiti National Team': 'Haiti',

    'Honduran National Team': 'Honduras',
    'Honduas': 'Honduras',

    'Japan National Team': 'Japan',
    'Japanese National Team': 'Japan',
    'Paraguayan National Team': 'Paraguay',
    'Singapore National Team': 'Singapore',
    'El Salvador National Team': 'El Salvador',
    'China National Team': 'China',
    'Chinese National Team': 'China',
    'Guatemalan National Team': 'Guatemala',
    'Bermuda National Team': 'Bermuda',
    'Colombian National Team': 'Colombia',
    'Colombia NT': 'Colombia',
    'Indonesia National Team': 'Indonesia',
    'Iran National Team': 'Iran',
    'Malaysia National Team': 'Malaysia',
    'Puerto Rico National Team': 'Puerto Rico',
    'Singapore National Team': 'Singapore',
    'U. S. National Team': 'United States',
    'Guatemala NT': 'Guatemala',
    'Haiti NT': 'Haiti',
    'Puerto Rico NT': 'Puerto Rico',
    'El Salvador National team': 'El Salvador',
    'Bermuda NT': 'Bermuda',
    'Mexico U-21 National team': 'Mexico U-21',

    'Unión Soviética': 'USSR',
    'USSR': 'U.S.S.R.',
    'U.S.S.R': 'U.S.S.R.',
    'Soviet Union': 'U.S.S.R',

    'Antigua Y Barbuda': 'Antigua and Barbuda',
    'Irlanda Del Norte': 'Northern Ireland',
    'Suazilandia': 'Swaziland',

    'Rp China Sub-17': 'China U-17',
    'Tayikistán Sub-17': 'Tajikstan U-17',
    'Irán Sub-17': 'Iran U-17',
    'Guinea Sub-17': 'Guinea U-17',
    'Unión Soviética Sub-17': 'U.S.S.R. U-17',
    'Togo Sub-17': 'Togo U-17',
    'Escocia Sub-17': 'Scotland U-17',
    'Bélgica Sub-17': 'Belgium U-17',
    'Emiratos Árabes Unidos Sub-17': 'United Arab Emirates U-17',
    'Polonia Sub-17': 'Poland U-17',
    'Portugal Sub-17': 'Portugal U-17',
    'Italia Sub-17': 'Italy U-17',
    'Haití Sub-17': 'Haiti U-17',
    'Hungría Sub-17': 'Hungary U-17',
    'Costa Rica Sub-17': 'Costa Rica U-17',
    'Arabia Saudita Sub-17': 'Saudi Arabia U-17',
    'Paraguay Sub-17': 'Paraguay U-17',
    'Colombia Sub-17': 'Colombia U-17',
    'Chile Sub-17': 'Chile U-17',
    'Perú Sub-17': 'Peru U-17',
    'Venezuela Sub-17': 'Venezuela U-17',
    'Bolivia Sub-17': 'Bolivia U-17',
    'Trinidad Y Tobago Sub-17': 'Trinidad and Tobago U-17',
    'Cuba Sub-17': 'Cuba U-17',
    'Honduras Sub-17': 'Honduras U-17',
    'Guatemala Sub-17': 'Guatemala U-17',
    'México Sub-17': 'Mexico U-17',
    'Japón Sub-17': 'Japan U-17',
    'Jamaica Sub-17': 'Jamaica U-17',
    'Congo Sub-17': 'Congo U-17',
    'Holanda Sub-17': 'Netherlands U-17',
    'Corea Del Norte Sub-17': 'North Korea U-17',
    'Francia Sub-17': 'France U-17',
    'Argentina Sub-17': 'Argentina U-17',
    'Uzbekistán Sub-17': 'Uzbekistan U-17',
    'Nueva Zelanda Sub-17': 'New Zealand U-17',
    'Uruguay Sub-17': 'Uruguay U-17',
    'Canadá Sub-17': 'Canada U-17',
    'Estados Unidos Sub-17': 'United States U-17'
    'Czech Republic U-17',
    'Rwanda Sub-17': 'Rwanda U-17',
    'Inglaterra Sub-17': 'England U-17',
    'Australia Sub-17': 'Australia U-17',
    'Alemania Sub-17': 'Germany U-17',
    'Ecuador Sub-17': 'Ecuador U-17',
    'Burkina Faso Sub-17': 'Burkina Faso U-17',
    'Panamá Sub-17': 'Panama U-17',
    'Brasil Sub-17': 'Brazil U-17',
    'Dinamarca Sub-17': 'Denmark U-17',
    'Costa De Marfil Sub-17': 'Ivory Coast U-17',
    'Rep. Checa Sub-17': 'Czech Republic U-17',
    'Finlandia Sub-17': 'Finland U-17',
    'Bahréin Sub-17': 'Bahrain U-17',
    'Sudán Sub-17': 'Sudan U-17',
    'Nigeria Sub-17': 'Nigeria U-17',
    'Siria Sub-17': 'Syria U-17',
    'Barbados- Sub-17': 'Barbados U-17',
    'Omán Sub-17': 'Oman U-17',
    'Egipto Sub-17': 'Egypt U-17',
    'Túnez Sub-17': 'Tunisia U-17',
    'Austria Sub-17': 'Austria U-17',
    'Ghana Sub-17': 'Ghana U-17',
    'España Sub-17': 'Spain U-17',
    'Qatar Sub-17': 'Qatar U-17',
    'Mali Sub-17': 'Mali U-17',
    'Tailandia Sub-17': 'Thailand U-17',

    'Haití Sub-20': 'Haiti U-20',
    'Estados Unidos Sub-20': 'United States U-20',
    'Curazao Sub-20': 'Curacao U-20',
    'Puerto Rico Sub-20': 'Puerto Rico U-20',
    'Jamaica Sub-20': 'Jamaica U-20',
    'Nicaragua Sub-20': 'Nicaragua U-20',
    'El Salvador Sub-20': 'El Salvador U-20',
    'Chile Sub-20': 'Chile U-20',
    'Paraguay Sub-20': 'Paraguay U-20',
    'Venezuela Sub-20': 'Venezuela U-20',
    'Bolivia Sub-20': 'Bolivia U-20',
    'Perú Sub-20': 'Brazil U-20',
    'Egipto Sub-20': 'Egypt U-20',
    'Guatemala Sub-20': 'Guatemala U-20',
    'Australia Sub-20': 'Australia U-20',
    'España Sub-20': 'Spain U-20',
    'Brasil Sub-20': 'Brazil U-20',
    'Ecuador Sub-20': 'Ecuador U-20',
    'Francia Sub-20': 'France U-20',
    'Colombia Sub-20': 'Colombia U-20',
    'Nueva Zelanda Sub-20': 'New Zealand U-20',
    'Camerún Sub-20': 'Cameroon U-20',
    'Uruguay Sub-20': 'Uruguay U-20',
    'Inglaterra Sub-20': 'England U-20',
    'Corea Del Norte Sub-20': 'North Korea U-20',
    'Mali Sub-20': 'Mali U-20',
    'Corea Del Sur Sub-20': 'South Korea U-20',
    'Portugal Sub-20': 'Portugal U-20',
    'Croacia Sub-20': 'Croatia U-20',
    'Arabia Saudita Sub-20': 'Saudi Arabia U-20',
    'México Sub-20': 'Mexico U-20',
    'Cuba Sub-20': 'Cuba U-20',
    'Costa Rica Sub-20': 'Costa Rica U-20',
    'Panamá Sub-20': 'Panama U-20',
    'Canadá Sub-20': 'Canada U-20',
    'Nigeria Sub-20': 'Nigeria U-20',
    'Argentina Sub-20': 'Argentina U-20',
    'Trinidad Y Tobago Sub-20': 'Trinidad and Tobago U-20',
    'Ghana Sub-20': 'Ghana U-20',
    'Grecia Sub-20': 'Greece U-20',
    'Turquía Sub-20': 'Turkey U-20',
    'Uzbekistán Sub-20': 'Uzbekistan U-20',
    'Irak Sub-20': 'Iraq U-20',
    'Guadalupe Sub-20': 'Guatemala U-20',
    'Honduras Sub-20': 'Honduras U-20',
    'Austria Sub-20': 'Austria U-20',


    'Chile Sub-22': 'Chile U-22',
    'México Sub-22': 'Mexico U-22',

    'Bielorrusia Sub-23': 'Belarus U-23',
    'Japón Sub-23': 'Japan U-23',
    'Portugal Sub-23': 'Portugal U-23',
    'Congo Rd Sub-23': 'DR Congo U-23',
    'Nigeria Sub-23': 'Nigeria U-23',
    'Brasil Sub-23': 'Brazil U-23',
    'Corea Del Sur Sub-23': 'South Korea U-23',
    'Colombia Sub-23': 'Colombia U-23',
    'Bélgica Sub-23': 'Belgium U-23',
    'Holanda Sub-23': 'Netherlands U-23',
    'Turquía Sub-23': 'Turkey U-23',
    'Honduras Sub-23': 'Honduras U-23',
    'Canadá Sub-23': 'Canada U-23',
    'Cuba Sub-23': 'Cuba U-23',
    'Trinidad Y Tobago Sub-23': 'Trinidad and Tobago U-23',
    'El Salvador Sub-23': 'El Salvador U-23',
    'Panamá Sub-23': 'Panama U-23',
    'Francia Sub-23': 'France U-23',
    'Marruecos Sub-23': 'Morocco U-23',
    'México Sub-23': 'Mexico U-23',
    'Estados Unidos Sub-23': 'United States U-23',

    'Corea Del Sur Olímpico': 'South Korea Olympic',
    'Gabón Olímpico': 'Gabon Olympic',
    'Senegal Olímpico': 'Senegal Olympic',
    'Egipto Olímpico': 'Egypt Olympic',
    'Brasil Olímpico': 'Brazil Olympic',
    'Suiza Olímpico': 'Switzerland Olympic',
    'Japón Olímpico': 'Japan Olympic',
    'México Olímpico': 'Mexico Olympic',
    'España Olímpico': 'Spain Olympic',
    'Honduras Olímpico': 'Honduras Olympic',
    'Marruecos Olímpico': 'Morocco Olympic',
    'Uruguay Olímpico': 'Uruguay Olympic',
    'Bielorrusia Olímpico': 'Belarus Olympic',
    'Nueva Zelanda Olímpico': 'New Zealand Olympic',
    'Gran Bretaña Olímpico': 'Great Britain Olympic',
    'Emiratos Árabes Olímpico': 'United Arab Emirates Olympic',

    'Gran Bretaña Femenil': 'Great Britain Women',
    'Camerún Femenil': 'Cameroon Women',
    'Sudáfrica Femenil': 'South Africa Women',
    'Costa Rica Femenil': 'Costa Rica Women',
    'Cuba Femenil': 'Cuba Women',
    'Guatemala Femenil': 'Guatemala Women',
    'Haití Femenil': 'Haiti Women',
    'México Femenil': 'Mexico Women',
    'Alemania Femenil': 'Germany Women',
    'Inglaterra Femenil': 'England Women',
    'Estados Unidos Femenil': 'United States Women',
    'Canadá Femenil': 'Canada Women',
    'Trinidad Y Tobago Femenil': 'Trinidad and Tobago Women',
    'Guyana Femenil': 'Guyana Women',
    'Corea Del Norte Femenil': 'North Korea Women',
    'Francia Femenil': 'France Women',
    'Nigeria Femenil': 'Nigeria Women',
    'Japón Femenil': 'Japan Women',
    'Colombia Femenil': 'Colombia Women',
    'Guinea Ecuatorial Femenil': 'Equatorial Guinea Women',
    'Brasil Femenil': 'Brazil Women',
    'Suecia Femenil': 'Sweden Women',
    'Australia Femenil': 'Australia Women',
    'Noruega Femenil': 'Norway Women',
    'Nueva Zelanda Femenil': 'New Zealand Women',
    'República Dominicana Femenil': 'Dominican Republic Women',

    'Irlanda Femenil Sub-17': 'Ireland Women U-17',
    'Alemania Femenil Sub-17': 'Germany Women U-17',
    'México Femenil Sub-17': 'Mexico Women U-17',
    'Corea Del Sur Femenil Sub-17': 'South Korea Women U-17',
    'Sudáfrica Femenil Sub-17': 'South Africa Women U-17',
    'Estados Unidos Femenil Sub-17': 'United States Women U-17',
    'Colombia Femenil Sub-17': 'Colombia Women U-17',
    'Chile Femenil Sub-17': 'Chile Women U-17',
    'Rp China Femenil Sub-17': 'China Women U-17',
    'Nueva Zelanda Femenil Sub-17': 'New Zealand Women U-17',
    'Japón Femenil Sub-17': 'Japan Women U-17',
    'Corea Del Norte Femenil Sub-17': 'North Korea Women U-17',
    'Trinidad Y Tobago Femenil Sub-17': 'Trinidad and Tobago Women U-17',
    'Uruguay Femenil Sub-17': 'Uruguay Women U-17',
    'Ghana Femenil Sub-17': 'Ghana Women U-17',
    'Francia Femenil Sub-17': 'France Women U-17',
    'Brasil Femenil Sub-17': 'Brazil Women U-17',
    'Gambia Femenil Sub-17': 'Gambia Women U-17',
    'Corea Del Sur Sub-17': 'South Korea U-17',
    'Canadá Femenil Sub-17': 'Canada Women U-17',

    'Japón Femenil Sub-20': 'Japan Women U-20',
    'México Femenil Sub-20': 'Mexico Women U-20',
    'Suiza Femenil Sub-20': 'Switzerland Women U-20',
    'Nueva Zelanda Femenil Sub-20': 'New Zealand Women U-20',
    'Italia Femenil Sub-20': 'Italy Women U-20',
    'Rp China Femenil Sub-20': 'China Women U-20',
    'Argentina Femenil Sub-20': 'Argentina Women U-20',
    'Inglaterra Femenil Sub-20': 'England Women U-20',
    'Ghana Femenil Sub-20': 'Ghana Women U-20',
    'Alemania Femenil Sub-20': 'Germany Women U-20',
    'Noruega Femenil Sub-20': 'Norway Women U-20',
    'Corea Del Sur Femenil Sub-20': 'South Korea Women U-20',
    'Estados Unidos Femenil Sub-20': 'United States Women U-20',
    'Costa Rica Femenil Sub-20': 'Costa Rica Women U-20',
    'Suecia Femenil Sub-20': 'Sweden Women U-20',
    'Colombia Femenil Sub-20': 'Colombia Women U-20',
    'Nigeria Femenil Sub-20': 'Nigeria Women U-20',
    'Corea Del Norte Femenil Sub-20': 'North Korea Women U-20',
    'Brasil Femenil Sub-20': 'Brazil Women U-20',
    'Canadá Femenil Sub-20': 'Canada Women U-20',
    'Panamá Femenil Sub-20': 'Panama Women U-20',

    'Jamaica Playa': 'Jamaica Beach',
    'Canadá Playa': 'Canada Beach',
    'Bahamas Playa': 'Bahamas Beach',
    'Italia Playa': 'Italy Beach',
    'Guatemala Playa': 'Guatemala Beach',
    'Costa Rica Playa': 'Costa Rica Beach',
    'Ucrania Playa': 'Ukraine Beach',
    'Estados Unidos Playa': 'United States Beach',
    'El Salvador Playa': 'El Salvador Beach',
    'España Playa': 'Spain Beach',
    'Rusia Playa': 'Russia Beach',
    'Brasil Playa': 'Brazil Beach',
    'México Playa': 'Mexico Beach',
    'Senegal Playa': 'Senegal Beach',
    'Portugal Playa': 'Portugal Beach',

    'México Panamericana': 'Mexico Panamerican',

    'Costa Rica J.P.': 'Costa Rica Panamerican',
    'Cuba J.P.': 'Cuba Panamerican',
    'Argentina J.P.': 'Argentina Panamerican',
    'Brasil J.P.': 'Brazil Panamerican',
    'México J.P.': 'Mexico Panamerican',
    'Ecuador J.P.': 'Ecuador Panamerican',
    'Uruguay J.P.': 'Uruguay Panamerican',
    'Trinidad Y Tobago J.P.': 'Trinidad and Tobago Panamerican',

    'Chile Femenil J.P.': 'Chile Women Panamerican',
    'Argentina Femenil J.P.': 'Argentina Women Panamerican',
    'Costa Rica Femenil J.P.': 'Costa Rica Women Panamerican',
    'Brasil Femenil J.P.': 'Brazil Women Panamerican',
    'Canadá Femenil J.P.': 'Canada Women Panamerican',

    'México Femenil J.P.': 'Mexico Women Panamerican',
    'Colombia Femenil J.P.': 'Colombia Women Panamerican',


    'Trinidad Y Tobago Femenil J.P.': 'Trinidad and Tobago Women Panamerican',




    }
